# -*- coding: utf-8 -*-
"""Cópia de Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLmHjrerrdSmgO44O232QUxHEMQ_l88M
"""

#Você é responsável por controlar as notas dos alunos de uma turma usando um dicionário. Com base no exemplo abaixo, realize as tarefas propostas:

# Dicionário com as notas de alguns alunos
#notas = {'Teo': 8.5, 'Cristiano': 8.9, 'Matson': 7.7}

#TAREFAS:
#1- Exiba a nota do aluno Matson.
#2- Adicione um novo aluno chamado "Bruna" com a nota 8.7.
#3- Atualize a nota do aluno "Teo" para 9.2.
#4- Verifique se o aluno "Carlos" está no dicionário.
#5- Apague o aluno "Matson" do dicionário.
#6- Adicione dois novos alunos com notas à sua escolha.
#7- Mostre todas as chaves (nomes dos alunos).
#8- Mostre todos os valores (notas dos alunos).
#9- Use o método .get() para tentar buscar a nota de "Islla", e retorne "Aluno não encontrado" caso ele não exista.
#10- Use o método .get() para tentar buscar a nota de algum aluno, e retorne "Aluno encontrado".

notas = {'Teo': 8.5, 'Cristiano': 8.9, 'Matson': 7.7}
print(notas['Matson'])

notas = {'Teo': 8.5, 'Cristiano': 8.9, 'Matson': 7.7}
notas['Bruna'] = 8.7
print(notas)

notas['Teo'] = 9.2
print(notas)

notas.get('Carlos', 'Aluno não encontrado')

del notas['Matson']
print(notas)

notas = {'Teo': 9.5, 'Cristiano': 8.9, 'Bruna': 8.7}
notas['Caio'] = 9.0
notas['Tiene'] = 8.5
print(notas)

notas.keys()

notas.values()

notas.get('Islla', 'Não encontrado!')

notas.get('Caio', 'Aluno encontrado!')